project:
  type: website
  output-dir: docs

resources:
  - CNAME

website:
  title: "Ahmed Elmokadem"
  site-url: "https://aelmokadem.github.io/aelmokadem"
  favicon: "img/favicon3.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- about.qmd
      - href: papers
        text: Papers
      - href: posts
        text: Blog
      - href: books
        text: Books
      - href: media
        text: Media
  page-footer:
    left: "(c) Ahmed Elmokadem, 2025â€“. [Disclaimer](disclaimer)"
  # comments:
  #   giscus:
  #     #repo: quarto-dev/quarto-web
  #     repo: aelmokadem/aelmokadem
  # margin-header: subscribe.html

format:
  html:
    theme:
      #- cosmo
      #- cerulean
      - flatly
      #- minty
      #- sketchy
      #- spacelab
      #- morph
      - brand
    include-after-body:
      - subscribe.html   # path relative to the project root
    css: styles.css
    toc: true

csl: assets/diabetologia.csl